foodsite/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', home_view, name='home-page'),

    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from . import views

app_name = 'restaurants'

urlpatterns = [
    path('register-restaurant/', views.register_restaurant_view, name='register-restaurant-page'),
    path('restaurant-details/', views.restaurant_details_view, name='restaurant-details-page'),
    path('dashboard/', views.dashboard_view, name='dashboard-view-page'),
    path('delete-category/<int:category_id>/', views.delete_category_view, name='delete-category-page'),
    path('category/<int:category_id>/items/', views.category_items_view, name='menu-item-page'),
    path('update-availability/', views.update_availability, name='update-availability-page'),
    path('update-item/<int:item_id>/', views.update_menu_item_view, name='update-item-page'),
    path('owner-items/', views.owner_menu_items_view, name='all-item-page'),
    path('all-items/', views.search_show_all_items, name='search-items-page'),
    path('restaurant-items/<int:restaurant_id>', views.indivual_restaurant_item, name='individual-restaurant-item-page'),
    path('delete-item/<int:item_id>/', views.delete_item_view, name='delete-item-page'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup-page'),
    path('login/', views.CustomLoginView.as_view(), name='login-page'),
    path('profile/', views.profile_view, name='profile-page'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout-page'),
    path('forgot-password/', views.forgot_password_view, name='forgot-password-page'),
    path('verify-otp/', views.verify_otp_view, name='verify-otp-page'),
    path('reset-password/', views.reset_password_view, name='reset-password-page'),
]

restaurants/models.py
from django.db import models
# from users.models import CustomUser
from django.contrib.auth import get_user_model

User = get_user_model()

class RestaurantOwnerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, limit_choices_to={'user_type': 'restaurant'}, related_name='restaurant_owner')
    restaurant_name = models.CharField(max_length=150)
    food_certificate = models.FileField(upload_to='certificates/', blank=False, null=False)
    is_approved = models.BooleanField(default=False )
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
class Restaurant(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, limit_choices_to={'user_type': 'restaurant'})    
    restaurant_owner_profile = models.OneToOneField(RestaurantOwnerProfile, on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField()
    phone = models.CharField(max_length=15)
    description = models.TextField(default='Tell the customer about your restaurant', blank=False)

    is_full_day_open = models.BooleanField(default=True)
    # Full Day Open/Close
    open_time = models.TimeField(null=True, blank=True)
    close_time = models.TimeField(null=True, blank=True)
    # Separate morning session
    morning_open_time = models.TimeField(null=True, blank=True)
    morning_close_time = models.TimeField(null=True, blank=True)
    # Separate evening session
    evening_open_time = models.TimeField(null=True, blank=True)
    evening_close_time = models.TimeField(null=True, blank=True)

    restaurant_image = models.ImageField(upload_to='restaurant_images/', blank=True, null=True)
    registered_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.restaurant_owner_profile.restaurant_name
    
class Category(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.restaurant} - {self.name}'
    
class MenuItem(models.Model):
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
    dish_name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    is_available = models.BooleanField(default=True)
    dish_image = models.ImageField(upload_to='dish_images/', blank=True, null=True)

    def __str__(self):
        return f'{self.dish_name} - ₹{self.price}'

restaurants/forms.py
from django import forms
from .models import RestaurantOwnerProfile, Restaurant, Category, MenuItem

class RestaurantOwnerProfileForm(forms.ModelForm):
    class Meta:
        model = RestaurantOwnerProfile
        fields = ['restaurant_name', 'food_certificate']

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = '__all__'
        widgets = {
            'open_time': forms.TimeInput(attrs={'type': 'time'}),
            'close_time': forms.TimeInput(attrs={'type': 'time'}),
            'morning_open_time': forms.TimeInput(attrs={'type': 'time'}),
            'morning_close_time': forms.TimeInput(attrs={'type': 'time'}),
            'evening_open_time': forms.TimeInput(attrs={'type': 'time'}),
            'evening_close_time': forms.TimeInput(attrs={'type': 'time'}),
        }
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['owner'].label_from_instance = lambda obj: obj.username

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {'name': forms.TextInput(attrs={'placeholder': 'Enter Category Name', 'class': 'form-control'})}

class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ['dish_name', 'description', 'price', 'is_available', 'dish_image']
        widget = {
            'is_available': forms.CheckboxInput(attrs={'class': 'form-cjeck-input'}),
        }

restaurants/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import RestaurantOwnerProfileForm, RestaurantForm, CategoryForm, MenuItemForm
from .models import RestaurantOwnerProfile, Restaurant, Category, MenuItem
from django.contrib import messages

from django.core.mail import send_mail
from django.conf import settings
# Handle AJAX POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json

from django.db.models import Q

@login_required
def register_restaurant_view(request):
    try:
        restaurant = request.user.restaurant_owner
        messages.info(request, "You have already submitted a request.")
        return redirect('users:profile-page')
    except RestaurantOwnerProfile.DoesNotExist:
        if request.method == 'POST':
            form = RestaurantOwnerProfileForm(request.POST, request.FILES)
            if form.is_valid():
                restaurant = form.save(commit=False)
                restaurant.user = request.user
                restaurant.save()
                messages.success(request, "Restaurant registration request submitted successfully.")
                return redirect('users:profile-page')
        else:
            form = RestaurantOwnerProfileForm
    return render(request, 'restaurants/register_restaurant.html', {'form': form})

def send_approval_email(user):
    subject = "Restaurant Approval Status"
    message = "Congratulations! Your restaurant registration has been approved."
    from_email = settings.DEFAULT_FROM_EMAIL
    recipient_list = [user.email]
    send_mail(subject, message, from_email, recipient_list)

@login_required
def restaurant_details_view(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST, request.FILES)
        if form.is_valid():
            restaurant = form.save(commit=False)
            restaurant.owner = request.user
            restaurant.restaurant_owner_profile = request.user.restaurant_owner
            restaurant.save()
            messages.success(request, "Restaurant details updated successfully!")
            return redirect('restaurants:dashboard-view-page')
        else:
            messages.error(request, 'Add details carufully.')
    else:
        form = RestaurantForm()
    return render(request, 'restaurants/restaurant_details.html', {'form': form})

@login_required
def dashboard_view(request):
    section = request.GET.get('section') # get section from query
    try:
        restaurant = Restaurant.objects.get(owner=request.user)
    except Restaurant.DoesNotExist:
        restaurant = None
    form = CategoryForm()
    categories = []
    if restaurant and section == 'item-category':
        categories = Category.objects.filter(restaurant=restaurant)
        if request.method == 'POST':
            form = CategoryForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name'].capitalize()
                if Category.objects.filter(name=name, restaurant=restaurant).exists():
                    messages.error(request, f"You have already added '{name}' category.")
                else:
                    category = form.save(commit=False)
                    category.name = name
                    category.restaurant = restaurant
                    category.save()
                    return redirect(f'{request.path}?section=item-category') # only redirect after success
    return render(request, 'restaurants/dashboard.html', {
        'restaurant': restaurant,
        'form': form,
        'categories': categories,
        'section': section})
    
@login_required
def delete_category_view(request, category_id):
    try:
        restaurant = Restaurant.objects.get(owner=request.user)
    except Restaurant.DoesNotExist:
        return redirect('restaurants:dashboard-view-page')
    category = get_object_or_404(Category, id=category_id, restaurant=restaurant)
    category.delete()
    return redirect(f'/restaurants/dashboard/?section=item-category')

@login_required
def category_items_view(request, category_id):
    restaurant = Restaurant.objects.get(owner=request.user)
    category = get_object_or_404(Category, id=category_id, restaurant=restaurant)
    items = MenuItem.objects.filter(category=category)
    form = MenuItemForm()
    if request.method == 'POST':
        form = MenuItemForm(request.POST, request.FILES)
        if form.is_valid():
            dish_name = form.cleaned_data['dish_name'].capitalize()
            if MenuItem.objects.filter(dish_name=dish_name, category=category).exists():
                messages.error(request, f"You have already added '{dish_name}' in '{category.name}'.")
            else:
                item = form.save(commit=False)
                item.dish_name = dish_name
                item.category = category
                item.save()
                messages.success(request, 'You have entered item details successfully.')
                return redirect('restaurants:menu-item-page', category_id=category.id)
    return render(request, 'restaurants/menu_items.html', {
        'category': category,
        'items': items,
        'form': form
    })

@login_required
def update_availability(request):
    item_id = request.POST.get('item_id')
    is_available = request.POST.get('is_available') == 'true'
    try:
        item = MenuItem.objects.get(id=item_id)
        item.is_available = is_available
        item.save()
        return JsonResponse({'status': 'success'})
    except MenuItem.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Item not found'}, status=404)
        
@login_required
def owner_menu_items_view(request):
    restaurant = Restaurant.objects.get(owner=request.user)
    categories = Category.objects.filter(restaurant=restaurant)
    all_items = MenuItem.objects.filter(category__restaurant=restaurant)

    return render(request, 'restaurants/all_items.html', {
        'categories': categories,
        'all_items': all_items
    })

def search_show_all_items(request):
    query = request.GET.get('q', '')
    # selected_category_id = request.GET.get('category')
    matched_restaurants = Restaurant.objects.none()
    matched_items = MenuItem.objects.none()
    # selected_category_items = None
    no_results = False

    if query:
        matched_restaurants = Restaurant.objects.filter(restaurant_owner_profile__restaurant_name__icontains=query)

        if not matched_restaurants.exists():
            matched_items = MenuItem.objects.filter(dish_name__icontains=query)
            if not matched_items.exists():
                no_results = True
    else:
        matched_items = MenuItem.objects.all()

    # if selected_category_id:
    #     try:
    #         selected_category = Category.objects.get(id=selected_category_id)
    #         selected_category_items = selected_category.items.all()
    #     except Category.DoesNotExist:
    #         selected_category_items = None

    return render(request, 'restaurants/all_items_for_user.html', {
        'matched_restaurants': matched_restaurants,
        'items': matched_items,
        # 'selected_category_items': selected_category_items,
        'query': query,
        # 'selected_category_id': selected_category_id,
        'no_results': no_results,
    })

def indivual_restaurant_item(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)
    category = Category.objects.filter(restaurant=restaurant)
    selected_category_id = request.GET.get('category')
    selected_category = None
    items = None

    if selected_category_id:
        try:
            selected_category = Category.objects.get(id=selected_category_id, restaurant=restaurant)
            items = MenuItem.objects.filter(category=selected_category)
        except Category.DoesNotExist:
            selected_category = None
            items = None

    return render(request, 'restaurants/restaurant_items.html', {
        'restaurant': restaurant,
        'category': category,
        'selected_category_id': selected_category_id,
        'selected_category': selected_category,
        'items': items,
    })

@login_required
def update_menu_item_view(request, item_id):
    item = get_object_or_404(MenuItem, id=item_id, category__restaurant__owner=request.user)
    
    if request.method == 'POST':
        form = MenuItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, 'Item updated successfully!')
            return redirect('restaurants:all-item-page') # After updating, redirect back to all items page
    else:
        form = MenuItemForm(instance=item) # for GET request (show the form first)
    
    return render(request, 'restaurants/update_item.html', {
        'form': form,
        'item': item,
    })

@login_required
def delete_item_view(request, item_id):
    dish_name = get_object_or_404(MenuItem, id=item_id)
    category_id = dish_name.category.id
    dish_name.delete()
    return redirect('restaurants:menu-item-page', category_id=category_id)

restaurants/templates/restaurants/all_items.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>All Items</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- Updated changes message -->
    <div id="availability-message" style="text-align: center; color: green; font-weight: bold;"></div>
    <!-- To display items -->
    <div class="item-container-grid">
        {% for item in all_items %}
            <div class="item-container">
                <div class="item-update-delete">
                    <a href="{% url 'restaurants:update-item-page' item.id %}" class="button-edit">✏️ Edit</a>
                    <a href="{% url 'restaurants:delete-item-page' item.id %}" class="button-delete" onclick="return confirm('Delete this item?')">❌ Delete</a>        
                </div>
                <h3>{{ item.dish_name }} : ₹{{ item.price }}</h3>
                <img class="item-img" src="{{ item.dish_image.url }}" alt="Dish Image">
                <br>
                <label>
                    <input type="checkbox"
                    class="availability-checkbox"
                    data-item-id="{{ item.id }}"
                    {% if item.is_available %}checked{% endif %}>
                    Available
                </label>
                <div class="item-description">
                    {{ item.description }}
                </div>
            </div>
        {% empty %}
            <p class="item-category">No items in this category.</p>
        {% endfor %}
    </div>
    {% endblock %}
</div>
{% include 'footer.html' %}

<script>
    document.querySelectorAll('.availability-checkbox').forEach(function(checkbox) {
        checkbox.addEventListener('change', function() {
            const itemId = this.dataset.itemId;
            const isAvailable = this.checked;
            const messageDiv = document.getElementById('availability-message');
            fetch("{% url 'restaurants:update-availability-page' %}", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: new URLSearchParams({
                    'item_id': itemId,
                    'is_available': isAvailable
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    if (isAvailable) {
                        messageDiv.innerText = 'Item marked as Available ✅';
                        messageDiv.style.color = 'green';
                    } else {
                        messageDiv.innerText = 'Item marked as Not Available ❌';
                        messageDiv.style.color = 'red';
                    }
                    setTimeout(() => {
                        messageDiv.innerText = '';
                    }, 3000);
                } else {
                    alert('Error updating them.');
                }
            });
        });
    });
</script>

restaurants/templates/restaurants/all_items_for_user.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    {% if query %}
        <h4>Searched results for: <strong>"{{ query }}"</strong></h4>
    {% endif %}
    <h2>All Items</h2>

    <!-- To display individual items -->
    {% if matched_restaurants %}
        {% for restaurant in matched_restaurants %}
            <div class="restaurant-container">
                <h2 class="restaurant-name"><a style="text-decoration: none;" href="{% url 'restaurants:individual-restaurant-item-page' restaurant.id %}">{{ restaurant.restaurant_owner_profile.restaurant_name }}</a></h2>
            </div>
        {% endfor %}
    {% endif %}

    {% if selected_category_items %}
        <h2>Items in Selected Category:</h2>
        <div class="item-container-grid">
            {% for item in selected_category_items %}
                <div class="item-container">
                    <h3>{{ item.dish_name }} : ₹{{ item.price }}</h3>
                    {% if item.dish_image %}
                        <img src="{{ item.dish_image.url }}" class="item-img" alt="{{ item.dish_name }}">
                    {% endif %}
                    {{ item.description }}
            </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if items %}
        <h2>Matched Items:</h2>
        <div class="item-container-grid">
            {% for item in items %}
            <div class="item-container">
                <strong>{{ item.dish_name }} - ₹{{ item.price }}</strong><br>
                {% if item.dish_image %}
                    <img src="{{ item.dish_image.url }}" alt="{{ item.dish_name }}" class="item-img">
                {% endif %}
                {{ item.description }}
            </div>
            {% endfor %}
        </div>
    
    {% elif no_results %}
        <p class="item-category">No matching restaurant or item found.<br>Please try a different search term.</p>
    {% endif %}
    {% endblock%}
</div>
{% include 'footer.html' %}

restaurants/templates/restaurants/dashboard.html
{% include 'header.html' %}
<div class="wrapper">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% if section == 'item-category' %}
    <h2>Menu (Item Categories)</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.name }}
        <button type="submit">Add Category +</button>
    </form> 
    <ul>
        {% for category in categories %}
        <div>
            <li>
                <a class="item-category" href="{% url 'restaurants:menu-item-page' category.id %}">{{ category.name }}</a>
                <a href="{% url 'restaurants:delete-category-page' category.id %}" onclick="return confirm('Delete this category?')">❌</a>
            </li>
            {% empty %}
            <li class="item-category">No categories added yet.</li>
            {% endfor %}
        </div>    
    </ul>
    {% endif %}
    <div class="dashboard-card">
        <h2>{{ restaurant.restaurant_owner_profile.restaurant_name|default:"Your Restaurant" }}</h2>
        {% if restaurant.restaurant_image %}
            <img src="{{ restaurant.restaurant_image.url }}" alt="Restaurant Image" style="max-width: 300px;">
        {% else %}
            <p>No image availabel</p>
        {% endif %}
        <div class="field"><label>Name: </label>{{ restaurant.owner.username }}</div>
        <div class="field"><label>Phone: </label>{{ restaurant.phone }}</div>
        <div class="field"><label>Email: </label>{{ restaurant.owner.email }}</div>
        <div class="field"><label>Address: </label>{{ restaurant.address }}</div>
        <div class="field"><label>Description: </label>{{ restaurant.description }}</div>
        <div class="field">
            <label>Open Type:</label>
            {% if restaurant.is_full_day_open %}
                Full Day ({{ restaurant.open_time }} - {{ restaurant.close_time }})
            {% else %}
                <div>Morning: {{ restaurant.morning_open_time }} - {{ restaurant.morning_close_time }}</div>
                <div>Eveninng: {{ restaurant.evening_open_time }} - {{ restaurant.evening_close_time }}</div>
            {% endif %}
        </div>

    </div>
    {% endblock %}
</div>

{% include 'footer.html' %}

restaurants/templates/restaurants/menu_items.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content%}
    <h2>{{ category.name|default:'All' }} Items</h2>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Item</button><br>
    </form>
    
    <!-- Updated changes message -->
    <div id="availability-message" style="text-align: center; color: green; font-weight: bold;"></div>
    <!-- To display items -->
    <div class="item-container-grid">
        {% for item in items %}
            <div class="item-container">
                <div class="item-update-delete">
                    <a href="{% url 'restaurants:update-item-page' item.id %}" class="button-edit">✏️ Edit</a>
                    <a href="{% url 'restaurants:delete-item-page' item.id %}" class="button-delete" onclick="return confirm('Delete this item?')">❌ Delete</a>        
                </div>
                <h3>{{ item.dish_name }} : ₹{{ item.price }}</h3>
                <img class="item-img" src="{{ item.dish_image.url }}" alt="Dish Image">
                <br>
                <label>
                    <input type="checkbox"
                    class="availability-checkbox"
                    data-item-id="{{ item.id }}"
                    {% if item.is_available %}checked{% endif %}>
                    Available
                </label>
                <div class="item-description">
                    {{ item.description }}
                </div>
            </div>
        {% empty %}
            <p class="item-category">No items in this category.</p>
        {% endfor %}
    </div>
    {% endblock %}
</div>
{% include 'footer.html' %}

<script>
    document.querySelectorAll('.availability-checkbox').forEach(function(checkbox) {
        checkbox.addEventListener('change', function() {
            const itemId = this.dataset.itemId;
            const isAvailable = this.checked;
            const messageDiv = document.getElementById('availability-message');
            fetch("{% url 'restaurants:update-availability-page' %}", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: new URLSearchParams({
                    'item_id': itemId,
                    'is_available': isAvailable
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    if (isAvailable) {
                        messageDiv.innerText = 'Item marked as Available ✅';
                        messageDiv.style.color = 'green';
                    } else {
                        messageDiv.innerText = 'Item marked as Not Available ❌';
                        messageDiv.style.color = 'red';
                    }
                    setTimeout(() => {
                        messageDiv.innerText = '';
                    }, 3000);
                } else {
                    alert('Error updating them.');
                }
            });
        });
    });
</script>

restaurants/templates/restaurants/register_restaurant.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Restaurant Registration</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Request</button>
    </form>
    {% endblock %}
</div>
{% include 'footer.html' %}

restaurants/templates/restaurants/restaurant_details.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Add Your Restaurant Details</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tag }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_erros }}
        <div><label for="id_owner">Owner: </label>{{ form.owner }}</div>
        <div><label for="id_address">Address: </label>{{ form.address }}</div>
        <div><label for="id_phone">Phone: </label>{{ form.phone }}</div>
        <div><label for="id_description">Description: </label>{{ form.description }}</div>
        <div><label for="id_is_full_day_open">Open full day? </label>{{ form.is_full_day_open }}</div>
        <div id="full-day-times" class="time-fields">
            <label for="id_open_time">Open Time: </label>{{ form.open_time }}
            <label for="id_close_time">Close Time: </label>{{ form.close_time }}
        </div>
        <div id="session-times" class="time-fields">
            <h4>Morning Session</h4>
            <label for="id_morning_open_time">Morning Open: </label>{{ form.morning_open_time }}
            <label for="id_morning_close_time">Morning Close: </label>{{ form.morning_close_time }}
            <h4>Evening Session</h4>
            <label for="id_evening_open_time">Evening Open: </label>{{ form.evening_open_time }}
            <label for="id_evening_close_time">Evening Close: </label>{{ form.evening_close_time }}
        </div>
        <div>
            <label for="id_restaurant_image">Upload Restaurant Photo: </label>{{ form.restaurant_image }}
        </div>
        <button type="submit">Submit</button>
    </form>
    {% endblock %}
</div>
<script>
    function toggleTimeFields() {
        const isFullDayOpen = document.getElementById('id_is_full_day_open');
        const fullDayTimes = document.getElementById('full-day-times');
        const SessionTimes = document.getElementById('session-times');
        if (isFullDayOpen.checked) {
            fullDayTimes.style.display = 'block';
            SessionTimes.style.display = 'none';
        } else {
            fullDayTimes.style.display = 'none';
            SessionTimes.style.display = 'block';
        }
    }
    document.addEventListener('DOMContentLoaded', function () {
        const isFullDayOpen = document.getElementById('id_is_full_day_open');
        toggleTimeFields(); // Inital Call
        isFullDayOpen.addEventListener('change', toggleTimeFields); // Listen for change
    });
    
</script>
{% include 'footer.html' %}

restaurants/templates/restaurants/restaurant_items.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <div class="restaurant-container">
        <h2 class="restaurant-name">{{ restaurant.restaurant_owner_profile.restaurant_name }}</h2>
        <h3>Menu</h3>
        {% for category in restaurant.category_set.all %}
            <a href="?q={{ query }}&category={{ category.id }}">    {{ category.name }}    |</a>
        {% endfor %}

        {% if selected_category_id %}
            <h2>Items in {{ selected_category.name }}:</h2>
            
            {% if items %}
                <div class="item-container-grid">
                    {% for item in items %}
                        <div class="item-container">
                            <h3>{{ item.dish_name }} - ₹{{ item.price }}</h3>
                            {% if item.dish_image %}
                                <img src="{{ item.dish_image.url }}" class="item-img" alt="{{ item.dish_name}}">
                            {% endif %}
                            {{ item.description }}
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p style="color: black;">No items available.</p>
            {% endif %}    
        {% endif %}
    </div>
    {% endblock %}
</div>
{% include 'footer.html' %}