foodsite/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', home_view, name='home-page'),

    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup-page'),
    path('login/', views.CustomLoginView.as_view(), name='login-page'),
    path('profile/', views.profile_view, name='profile-page'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout-page'),
    path('forgot-password/', views.forgot_password_view, name='forgot-password-page'),
    path('verify-otp/', views.verify_otp_view, name='verify-otp-page'),
    path('reset-password/', views.reset_password_view, name='reset-password-page'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.validators import username_validator, email_validator

# Customize the user fields and behavior: Email - based login | User Roles (Customer, Restaurant Owner) | Extra info like phone & address
class CustomUser(AbstractUser):
    USER_TYPES = (
        ('admin', 'Admin'),
        ('customer', 'Customer'),
        ('restaurant', 'Restaurant Owner'),
    )
    # Custom username with space allowed, and not unique
    username = models.CharField(max_length=150, unique=False, validators=[username_validator])
    # Email: must be unique and validated
    email = models.EmailField(unique=True, validators=[email_validator])
    user_type = models.CharField(max_length=20, choices=USER_TYPES, default='customer')
    phone = models.CharField(max_length=15, blank=True)
    address = models.TextField()
    # This tells Django to use email as the Login field
    USERNAME_FIELD = 'email' # important
    REQUIRED_FIELDS = ['username', 'phone', 'address', 'user_type'] # or any other required fields
    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phone', 'address', 'user_type', 'password1', 'password2']

class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField( # Override 'username' field label and type
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}),
        label="Email",
    )

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField()

class OTPVerificationForm(forms.Form):
    otp = forms.CharField(max_length=6)

class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('new_password') != cleaned_data.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data
    

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth import login #/ auto-login users after signup
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from restaurants.models import RestaurantOwnerProfile

from .forms import CustomUserCreationForm, EmailLoginForm, ForgotPasswordForm, OTPVerificationForm, ResetPasswordForm

import random
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()

# from django.db import connection
# print("Connected DB:", connection.settings_dict['NAME'])

def home_view(request):
    return render(request, 'home.html')

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data.get('email')
            login_url = reverse('users:login-page')
            messages.success(request, 'Signup successful! Please log in.')
            return redirect(f"{login_url}?email={email}")
            # return redirect('users:login-page') # login(request, user)
            # return redirect('/')
        else:
            messages.error(request, 'Signup failed. Please correct the errors below.')
    else:
        form = CustomUserCreationForm()

    return render(request, 'users/signup.html', {'form': form})

@login_required
def profile_view(request):
    user = request.user
    restaurant_profile = None
    restaurant_registration_missing = False

    try:
        restaurant_profile = user.restaurant_owner # Used related name
        if restaurant_profile.is_approved:
            messages.success(request,'✅ Your restaurant has been approved!')
        else:
            messages.info(request, '⏳ Your registration request is pending.')
    except RestaurantOwnerProfile.DoesNotExist:
        if user.user_type == 'Resataurant Owner':
            messages.error(request, '❌ Your registration request was not found (possibly rejected).')
            restaurant_registration_missing = True

    return render(request, 'users/profile.html', {
        'restaurant_profile': restaurant_profile,
        'restaurant_registration_missing': restaurant_registration_missing,
    })

def forgot_password_view(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
                otp = str(random.randint(100000, 999999))
                request.session['reset_email'] = email
                request.session['reset_otp'] = otp
                send_mail(
                    subject='Your OTP for Password Reset',
                    message=f'Your OTP is: {otp}',
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[email],
                    fail_silently=False
                )
                return redirect('users:verify-otp-page')
            except User.DoesNotExist:
                messages.error(request, 'No account found with this email.')
    else:
        form = ForgotPasswordForm()
    return render(request, 'users/forgot_password.html', {'form': form})

def verify_otp_view(request):
    if request.method == 'POST':
        form = OTPVerificationForm(request.POST)
        if form.is_valid():
            input_otp = form.cleaned_data['otp']
            session_otp = request.session.get('reset_otp')
            if input_otp == session_otp:
                return redirect('users:reset-password-page')
            else:
                messages.error(request, 'Invalid OTP. Please try again.')
    else:
        form = OTPVerificationForm()
    return render(request, 'users/verify_otp.html', {'form': form})

def reset_password_view(request):
    email = request.session.get('reset_email')
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['new_password']
            try:
                user = User.objects.get(email=email)
                user.set_password(password)
                user.save()
                messages.success(request, 'Password updated successfully! You can now log in.')
                # Clear session data
                request.session.flush()
                return redirect('users:login-page')
            except User.DoesNotExist:
                messages.error(request, 'User not found. Please try agian.')
    else:
        form = ResetPasswordForm()
    return render(request, 'users/reset_password.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    authentication_form = EmailLoginForm # Use our custom Login form
    
    def form_valid(self, form):
        messages.success(self.request, 'Logged in successfully!')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Login failed. Please try again.')
        return super().form_invalid(form)
    
    def get_success_url(self):
        return reverse_lazy('users:profile-page')

users/templates/users/forgot_password.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Forgot Password</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send OTP</button>
    </form>
    {% endblock %}
</div>
{% include 'footer.html' %}

users/templates/users/login.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Login</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="{% url 'users:login-page' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <p><a href="{% url 'users:forgot-password-page' %}" class="highlight-link">Forgot Password?</a></p>
    <p>Don't have an account? <a href="{% url 'users:signup-page' %}" class="highlight-link">Register here...</a></p>
    {% endblock %}
</div>
{% include 'footer.html' %}

users/templates/users/profile.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h2>Welcome, {{ user.username }}!</h2>
    <h4>( {{ user.user_type|capfirst }} Owner )</h4>
    {% if restaurant_profile %}
        <ul class="messages">
            <li class="{{ message.tags }}">{{ message }}</li>
        </ul>
    {% endif %}
    <table class="restaurant-table">
        
    </table>
    <table class="profile-table">
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Phone</th>
            <td>{{ user.phone }}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td>{{ user.address }}</td>
        </tr>
    </table>
    {% endblock %}
</div>

users/templates/users/reset_password.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Reset Your Password</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Password</button>
    </form>
    {% endblock %}
</div>
{% include 'footer.html' %}

users/templates/users/signup.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Signup</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="{% url 'users:signup-page' %}">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.errors %}
            <ul class="error">
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <button type="submit">Register</button>
    </form>
    <p>Already have an account? <a href="{% url 'users:login-page' %}" class="highlight-link">Login here...</a></p>
    {% endblock %}
</div>
{% include 'footer.html' %}

users/templates/users/verify_otp.html
{% include 'header.html' %}
<div class="wrapper">
    {% block content %}
    <h2>Enter OTP</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Verify</button>
    </form>
    {% endblock %}
</div>
{% include 'footer.html' %}